version: '3.4' 
services:
  waf:
    container_name: waf
    build:
        context: .
    ports:
        - "80:80"
    restart: on-failure
    networks:
        - modsec_network
volumes:
    esdata1:
        driver: local

networks:
    modsec_network:
        driver: bridge

